### PR TITLE
Cache Go dependencies using a vendor/ directory

### PR DESCRIPTION
**Pull request by afiune**
Switching to use a `vendor/` directory to have all dependencies inside
this repository and speed up our CI just a little bit more.

Signed-off-by: Salim Afiune <afiune@chef.io>

### CODE REVIEW

**Comment by tas50** [comment]
You might want to look at how we handle the deps for ruby in DK. It avoids putting it all in the repo which really quickly ends up ballooning the repo size

**Comment by afiune** [comment]
I think uploading dependencies to an S3 bucket is fine for Ruby/ChefDk case since you have to do some compilation of native extensions, also since you will have to do the tree resolution, and maybe more. (Size of the cached gems)

In this project I don’t think we will have such number of dependencies, additionally go has a very particular way of pulling down dependencies, so downloading them from github is not that big of a deal, but internally at Chef we have a requirement to not have dependencies so for that reason I had to move us to a vendor directory. 

Still, this is the first step to move things ahead, meaning that If this directory grows insanely, we will be able to do your magic in the future. (uploading and downloading from a S3 bucket)

**Comment by afiune** [comment]
Hi

**Comment by afiune** [comment]
Code Coverage:
```github.com/chef/chef-analyze/pkg/config/config.go:55: ActiveProfile 100.0% github.com/chef/chef-analyze/pkg/config/config.go:60: SwitchProfile 85.7% github.com/chef/chef-analyze/pkg/config/config.go:77: FromViper 84.6% github.com/chef/chef-analyze/pkg/config/config.go:109: NewDefault 100.0% github.com/chef/chef-analyze/pkg/config/config.go:114: New 80.0% github.com/chef/chef-analyze/pkg/config/config.go:147: FindCredentialsFile 100.0% github.com/chef/chef-analyze/pkg/config/config.go:161: FindConfigFile 84.2% github.com/chef/chef-analyze/pkg/reporting/chef_client.go:14: NewChefClient 42.9% github.com/chef/chef-analyze/pkg/reporting/cookbooks.go:12: Cookbooks 21.4% github.com/chef/chef-analyze/pkg/reporting/nodes.go:11: Nodes 0.0% total: (statements) 60.0%```

**Comment by afiune** [comment]
# Code Coverage Code details | Function name | % Coverage ----------------------------------------- github.com/chef/chef-analyze/pkg/config/config.go:55: | ActiveProfile | 100.0% github.com/chef/chef-analyze/pkg/config/config.go:60: | SwitchProfile | 85.7% github.com/chef/chef-analyze/pkg/config/config.go:77: | FromViper | 84.6% github.com/chef/chef-analyze/pkg/config/config.go:109: | NewDefault | 100.0% github.com/chef/chef-analyze/pkg/config/config.go:114: | New | 80.0% github.com/chef/chef-analyze/pkg/config/config.go:147: | FindCredentialsFile | 100.0% github.com/chef/chef-analyze/pkg/config/config.go:161: | FindConfigFile | 84.2% github.com/chef/chef-analyze/pkg/reporting/chef_client.go:14: | NewChefClient | 42.9% github.com/chef/chef-analyze/pkg/reporting/cookbooks.go:12: | Cookbooks | 21.4% github.com/chef/chef-analyze/pkg/reporting/nodes.go:11: | Nodes | 0.0% total: | (statements) | 60.0%

**Pull request merged**
